### ISSUE TITLE
Demo app is broken

### ISSUE THREAD

**Issue by magick93** [bloomreach/bloomreach-spartacus-storefront#1]
Hi

I tried to view your demo app, but no content is displayed. In the browser console is the following error:

```
main.0a11efe8475a6be19520.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'data')
    at hn.<anonymous> (main.0a11efe8475a6be19520.js:1:1868706)
    at Generator.next (<anonymous>)
    at St (main.0a11efe8475a6be19520.js:1:1861860)
    at v.invoke (polyfills.ccf45bcbd45d2aadd2d6.js:1:6557)
    at Object.onInvoke (main.0a11efe8475a6be19520.js:1:179786)
    at v.invoke (polyfills.ccf45bcbd45d2aadd2d6.js:1:6497)
    at M.run (polyfills.ccf45bcbd45d2aadd2d6.js:1:1953)
    at polyfills.ccf45bcbd45d2aadd2d6.js:1:16787
    at v.invokeTask (polyfills.ccf45bcbd45d2aadd2d6.js:1:7175)
    at Object.onInvokeTask (main.0a11efe8475a6be19520.js:1:179602)
```

**Comment by shivanayakd** [comment]
Hi, Could you please confirm if all the environment variables are set?
https://github.com/bloomreach/bloomreach-spartacus-storefront#set-environment-varaibles

**Comment by magick93** [comment]
I'm referring to https://brx-spartacus-latest.netlify.app/

**Comment by shivanayakd** [comment]
Please add the endpoint parameter to the URL to specify the brX SaaS instance to fetch the page model from, it should look something like:
https://brx-spartacus-latest.netlify.app/?endpoint=http://localhost:8080/delivery/site/v1/channels/spartacus/pages

* Replace the localhost:8080 with the hosted brX SaaS instance domain name
